apiVersion: v1
kind: Secret
metadata:
  name: $APP_NAME
type: Opaque
stringData:
  DATABASE_CLIENT: "${DATABASE_CLIENT}"
  DATABASE_HOST: "${DATABASE_HOST}"
  DATABASE_PORT: "${DATABASE_PORT}"
  DATABASE_NAME: "DATABASE_GENERATED"
  DATABASE_USERNAME: "${DATABASE_USERNAME}"
  DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
  DATABASE_SSL: "${DATABASE_SSL}"
  DATABASE_SCHEMA: "${DATABASE_SCHEMA}"
  EMAIL_DEFAULT_FROM: "${EMAIL_DEFAULT_FROM}"
  # STORAGE_ACCOUNT: "${STORAGE_ACCOUNT}"
  # STORAGE_ACCOUNT_KEY: "${STORAGE_ACCOUNT_KEY}"
  # STORAGE_URL: "${STORAGE_URL}"
  # STORAGE_CONTAINER_NAME: "${STORAGE_CONTAINER_NAME}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_ACCESS_KEY_ID_SES: "${AWS_ACCESS_KEY_ID_SES}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_SECRET_ACCESS_KEY_SES: "${AWS_SECRET_ACCESS_KEY_SES}"
  AWS_REGION: "${AWS_REGION}"
  AWS_BUCKET: "${AWS_BUCKET}"
  AWS_BUCKET_SUBDIRECTORY: "${AWS_BUCKET_SUBDIRECTORY}"
  AWS_CDN_DOMAIN: "${AWS_CDN_DOMAIN}"
  AWS_URL_SES: "${AWS_URL_SES}"
  APP_KEYS: "${APP_KEYS}"

