version: '3'
services:
  strapi:
    container_name: devportal_strapi_latest
    image: ${DOCKER_IMAGE_PATH}:${$CI_COMMIT_SHORT_SHA}
    environment:
      DATABASE_CLIENT: "${DATABASE_CLIENT}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_NAME: "DATABASE_GENERATED"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_SSL: "${DATABASE_SSL}"
      STORAGE_ACCOUNT: "${STORAGE_ACCOUNT}"
      STORAGE_ACCOUNT_KEY: "${STORAGE_ACCOUNT_KEY}"
      STORAGE_URL: "${STORAGE_URL}"
      STORAGE_CONTAINER_NAME: "${STORAGE_CONTAINER_NAME}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      AWS_BUCKET: "${AWS_BUCKET}"
      AWS_BUCKET_SUBDIRECTORY: "${AWS_BUCKET_SUBDIRECTORY}"
      AWS_CDN_DOMAIN: "${AWS_CDN_DOMAIN}"
    volumes:
      - ./app:/srv/app
    ports:
      - ${PORT}:1337
    restart: always
    networks:
      - networks_cloudappi
networks:
    networks_cloudappi:
        external: true

