apiVersion: v1
kind: Service
metadata:
  name: CI_PROJECT_NAME
  labels:
    app: CI_PROJECT_NAME
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 1337
  selector:
    app: CI_PROJECT_NAME

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {} 
  name: CI_PROJECT_NAME
data:
  DATABASE_HOST: "DATABASE_HOST_VALUE"
  DATABASE_PORT: "DATABASE_PORT_VALUE"
  DATABASE_NAME: "DATABASE_NAME_VALUE"
  DATABASE_USERNAME: "DATABASE_USERNAME_VALUE"
  DATABASE_PASSWORD: "DATABASE_PASSWORD_VALUE"
  STORAGE_ACCOUNT: "STORAGE_ACCOUNT_VALUE"
  STORAGE_ACCOUNT_KEY: "STORAGE_ACCOUNT_KEY_VALUE"
  STORAGE_URL: "STORAGE_URL_VALUE"
  STORAGE_CONTAINER_NAME: "STORAGE_CONTAINER_NAME_VALUE"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: CI_PROJECT_NAME
  labels:
    app: CI_PROJECT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CI_PROJECT_NAME
  template:
    metadata:
      labels:
        app: CI_PROJECT_NAME
    spec:
      containers:
        - name: CI_PROJECT_NAME
          image: CI_REGISTRY_IMAGE:DEPLOY_VERSION
          ports:
            - name: http
              containerPort: 1337
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: CI_PROJECT_NAME
      imagePullSecrets:
            - name: gitlab-auth-cloudappi

